@startuml
autoactivate on
participant ": Timetable" as Timetable
participant ": Course" as Course

[-> Timetable : removeCourse(courseCode)
loop until current course matches target course code or end of list reached
    Timetable -> Timetable : courses.get(i).get(j)
    Timetable --> Timetable : currCourse
    Timetable -> Course : currCourse.getCourseCode()
    Course --> Timetable : currCourseCode
    deactivate Course
end

opt target course code found
    Timetable -> Timetable : courses.get(i).remove(j)
    deactivate Timetable
    Timetable -> Timetable : courses.get(i).isEmpty()
    deactivate Timetable
    opt inner ArrayList representing the term of course removed is now empty
        Timetable -> Timetable : courses.remove(i)
        deactivate Timetable
    end
end

[<-- Timetable : whether target course code was found
deactivate Timetable
@enduml